stages:
- stage: build
  displayName: Version and build
  jobs:

  - job: run_build
    displayName: Build, publish AzureCli Module
    variables:
      Module.Path: $(Module.Name)/$(Module.Name)
      Module.ArtifactPath: $(build.artifactStagingDirectory)/$(Module.Name)
      Repository.ArtifactPath: $(build.artifactStagingDirectory)/Repository
      Repository.Name: Local$(Module.Name)PowerShell
      SolutionFile: AzureCli.sln
      CompanyName: Daniël te Winkel
      Author: Daniël te Winkel
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    pool:
      vmImage: windows-latest
    steps:

    - task: GitVersion@5
      displayName: Determine Version using GitVersion
      inputs:
        configFilePath: GitVersion.yml

    - task: CopyFiles@2
      displayName: Copy Module files
      inputs:
        SourceFolder: $(Module.Path)
        Contents: '**'
        TargetFolder: $(Module.ArtifactPath)

    - pwsh: |
        $modulePath = (Join-Path "$(Module.ArtifactPath)" "$(Module.Name).psd1")
        $year = ([DateTime]"$(GitVersion.CommitDate)").Year
        $copyright = "Copyright © ${year}, $(CompanyName). All rights reserved."
        $updateParameters = @{
          Path = $modulePath
          ModuleVersion = '$(GitVersion.MajorMinorPatch)'
          Copyright = $copyright
          Author = '$(Author)'
          CompanyName = '$(CompanyName)'
        }
        if("$(GitVersion.PreReleaseTag)" -ne "")
        {
          $preReleaseTag = '$(GitVersion.PreReleaseTag)' -replace '[^a-zA-Z0-9]', ''
          $updateParameters.Add("Prerelease", "${preReleaseTag}")
        }
        Update-ModuleManifest @updateParameters
        # make sure the ModuleManifest is in the right encoding.
        $manifest = Get-Content $modulePath
        $manifest | Out-File -Encoding utf8BOM $modulePath
      displayName: Update Module manifest

    - pwsh: |
        Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
        Invoke-ScriptAnalyzer "$(Module.ArtifactPath)" -EnableExit
      displayName: Run PowerShell ScriptAnalyzer

    - pwsh: |
        if(-not (Test-Path $(Repository.ArtifactPath)))
        {
            New-Item -Path $(Repository.ArtifactPath) -ItemType Directory
        }
        Remove-Item (Join-Path $(Repository.ArtifactPath) "$(Module.Name)*.nupkg") -Force
        Register-PSRepository -Name $(Repository.Name) -SourceLocation $(Repository.ArtifactPath) -InstallationPolicy Trusted
        Publish-Module -Path $(Module.ArtifactPath) -Repository $(Repository.Name) -Force
      displayName: Create NuGet package for Module

    - publish: $(Module.ArtifactPath)
      artifact: $(Module.ArtifactName)
      displayName: Publish Module Artifact

    - publish: $(Repository.ArtifactPath)
      artifact: $(Repository.ArtifactName)
      displayName: Publish Repository Artifact
