parameters:
  Condition: succeeded()
  Repository.Name:
  Repository.FeedUrl:
  Repository.ApiKey:

stages:

  - stage: publish_${{ parameters.Repository.Name }}
    displayName: Publish to ${{ parameters.Repository.Name }}
    condition: ${{ parameters.Condition }}
    jobs:

    - deployment: publish_${{ parameters.Repository.Name }}_job
      displayName: Publish to ${{ parameters.Repository.Name }}
      environment: $(Module.Name)-${{ parameters.Repository.Name }}
      pool:
        vmImage: windows-latest
      strategy:
        runOnce:
          deploy:
            steps:
            - pwsh: |
                echo "Hello"
              displayName: "Publish module to ${{ parameters.Repository.Name }} (${{ parameters.Repository.FeedUrl }})"
