parameters:
  Condition: succeeded()
  RepositoryConnection:

stages:

  - stage: publish_${{ parameters.RepositoryName }}
    displayName: Publish to ${{ parameters.RepositoryName }}
    condition: ${{ parameters.Condition }}
    jobs:

    - deployment: publish_${{ parameters.RepositoryName }}_job
      displayName: Publish to ${{ parameters.RepositoryName }}
      environment: $(Module.Name)-${{ parameters.RepositoryName }}
      pool:
        vmImage: windows-latest
      strategy:
        runOnce:
          deploy:
            steps:

            - task: NuGetCommand@2
              displayName: Publish module to gallery feed
              inputs:
                command: push
                packagesToPush: $(Build.ArtifactStagingDirectory)/$(Repository.ArtifactName)/*.nupkg
                nuGetFeedType: external
                publishFeedCredentials: ${{ parameters.RepositoryConnection }}
                verbosityPush: Normal